# Copyright (C) 2020 Really Awesome Technology Ltd
#
# This file is part of RACTF.
#
# RACTF is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RACTF is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with RACTF.  If not, see <https:#www.gnu.org/licenses/>.

name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --shamefully-hoist

      - name: Run Build
        run: pnpm run build
        env:
          CI: "false"
          RACTF_USING_CADDY: "true"

      - name: Publish artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
