name: Build Docker Container

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache docker layers
      uses: satackey/action-docker-layer-caching@v0.0.4
      with:
        key: docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-{hash}
        restore-keys: docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-

    - name: Build challenge
      run: docker build -t ractf/shell:latest .

    - name: Login to Docker Hub
      run: docker login --username ractf --password ${{ secrets.password }}
      
    - name: Push to Docker Hub
      run: docker push ractf/shell:latest
